export default function Logo() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="30"
      height="30"
      fill="none"
      viewBox="0 0 128 128"
      id="dragable"
    >
      <circle
        cx="82"
        cy="30"
        r="4"
        fill="#000"
        stroke="#000"
        stroke-width="7"
      ></circle>
      <circle
        cx="82"
        cy="64"
        r="4"
        fill="#000"
        stroke="#000"
        stroke-width="7"
      ></circle>
      <circle
        cx="82"
        cy="98"
        r="4"
        fill="#000"
        stroke="#000"
        stroke-width="7"
      ></circle>
      <circle
        cx="46"
        cy="30"
        r="4"
        fill="#000"
        stroke="#000"
        stroke-width="7"
      ></circle>
      <circle
        cx="46"
        cy="64"
        r="4"
        fill="#000"
        stroke="#000"
        stroke-width="7"
      ></circle>
      <circle
        cx="46"
        cy="98"
        r="4"
        fill="#000"
        stroke="#000"
        stroke-width="7"
      ></circle>
    </svg>
  );
}
